-- Trading System Tables initialization
-- Creates additional tables for NewsCards, Scenarios, Positions, Orders, Decision Logs, and Agent Performance

-- ====================
-- 1. NEWSCARDS TABLE
-- ====================
-- Stores structured news events with impact assessment and ticker associations
CREATE TABLE IF NOT EXISTS newscards (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker VARCHAR(10) NOT NULL,
    event_type VARCHAR(50) NOT NULL, -- 'EARNINGS', 'FDA', 'MERGER', 'MACRO', 'SENTIMENT', etc.
    impact_score NUMERIC(3, 2) CHECK (impact_score >= -1 AND impact_score <= 1), -- -1 (very negative) to +1 (very positive)
    confidence NUMERIC(3, 2) CHECK (confidence >= 0 AND confidence <= 1), -- 0 to 1
    title TEXT NOT NULL,
    summary TEXT,
    full_text TEXT,
    source VARCHAR(100),
    source_url TEXT,
    published_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    enriched_at TIMESTAMPTZ,
    -- Sentiment analysis
    sentiment_score NUMERIC(3, 2),
    sentiment_label VARCHAR(20), -- 'POSITIVE', 'NEGATIVE', 'NEUTRAL'
    -- Entity extraction
    entities JSONB, -- {"organizations": [...], "persons": [...], "locations": [...]}
    keywords TEXT[],
    -- Metadata
    priority VARCHAR(10) DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSED', 'ARCHIVED')),
    tags TEXT[],
    metadata JSONB,
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for newscard queries
CREATE INDEX IF NOT EXISTS idx_newscards_ticker ON newscards (ticker);
CREATE INDEX IF NOT EXISTS idx_newscards_event_type ON newscards (event_type);
CREATE INDEX IF NOT EXISTS idx_newscards_published_at ON newscards (published_at DESC);
CREATE INDEX IF NOT EXISTS idx_newscards_ingested_at ON newscards (ingested_at DESC);
CREATE INDEX IF NOT EXISTS idx_newscards_priority ON newscards (priority);
CREATE INDEX IF NOT EXISTS idx_newscards_status ON newscards (status);
CREATE INDEX IF NOT EXISTS idx_newscards_impact_score ON newscards (impact_score DESC NULLS LAST);

-- GIN indexes for JSONB and array columns
CREATE INDEX IF NOT EXISTS idx_newscards_entities_gin ON newscards USING GIN (entities);
CREATE INDEX IF NOT EXISTS idx_newscards_keywords_gin ON newscards USING GIN (keywords);
CREATE INDEX IF NOT EXISTS idx_newscards_tags_gin ON newscards USING GIN (tags);

-- ====================
-- 2. SCENARIOS TABLE
-- ====================
-- Stores trading scenarios generated by IA for different conditions
CREATE TABLE IF NOT EXISTS scenarios (
    scenario_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker VARCHAR(10) NOT NULL,
    scenario_version INT NOT NULL DEFAULT 1,
    scenario_name VARCHAR(100) NOT NULL,
    -- Conditions
    trigger_conditions JSONB NOT NULL, -- {"price_above": 150, "volume_spike": 2.0, "news_impact": 0.5}
    exit_conditions JSONB NOT NULL, -- {"target_profit": 0.05, "stop_loss": 0.02, "time_limit": "1h"}
    -- Strategy
    action VARCHAR(10) NOT NULL CHECK (action IN ('BUY', 'SELL', 'HOLD', 'WAIT')),
    position_size NUMERIC(10, 4), -- % of portfolio or absolute shares
    timeframe VARCHAR(20), -- '1m', '5m', '1h', '1d'
    strategy_type VARCHAR(50), -- 'MOMENTUM', 'MEAN_REVERSION', 'BREAKOUT', 'NEWS_DRIVEN', etc.
    -- Risk management
    max_risk NUMERIC(5, 4), -- Maximum risk as % of portfolio
    confidence_threshold NUMERIC(3, 2), -- Minimum confidence to execute
    -- Metadata
    ia_model VARCHAR(50), -- 'claude-3-opus', 'gpt-4o', etc.
    ia_reasoning TEXT, -- Explanation from IA
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    valid_until TIMESTAMPTZ, -- Scenario expiration
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXECUTED', 'EXPIRED', 'CANCELLED')),
    priority INT DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
    -- Backtesting results (if available)
    backtest_results JSONB, -- {"win_rate": 0.65, "avg_return": 0.03, "sharpe": 1.5}
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (ticker, scenario_version, scenario_name)
);

-- Indexes for scenario queries
CREATE INDEX IF NOT EXISTS idx_scenarios_ticker ON scenarios (ticker);
CREATE INDEX IF NOT EXISTS idx_scenarios_status ON scenarios (status);
CREATE INDEX IF NOT EXISTS idx_scenarios_generated_at ON scenarios (generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_scenarios_valid_until ON scenarios (valid_until DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_scenarios_priority ON scenarios (priority DESC);
CREATE INDEX IF NOT EXISTS idx_scenarios_action ON scenarios (action);

-- ====================
-- 3. POSITIONS TABLE
-- ====================
-- Tracks open and closed trading positions
CREATE TABLE IF NOT EXISTS positions (
    position_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker VARCHAR(10) NOT NULL,
    action VARCHAR(10) NOT NULL CHECK (action IN ('LONG', 'SHORT')),
    -- Entry
    entry_price NUMERIC(20, 8) NOT NULL,
    entry_quantity NUMERIC(20, 8) NOT NULL,
    entry_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    entry_order_id UUID, -- Reference to orders table
    -- Current state
    current_price NUMERIC(20, 8),
    current_quantity NUMERIC(20, 8), -- May differ from entry if partial close
    unrealized_pnl NUMERIC(20, 8),
    unrealized_pnl_pct NUMERIC(10, 4),
    last_price_update TIMESTAMPTZ,
    -- Exit (if closed)
    exit_price NUMERIC(20, 8),
    exit_quantity NUMERIC(20, 8),
    exit_timestamp TIMESTAMPTZ,
    exit_order_id UUID, -- Reference to orders table
    realized_pnl NUMERIC(20, 8),
    realized_pnl_pct NUMERIC(10, 4),
    -- Risk management
    stop_loss NUMERIC(20, 8),
    take_profit NUMERIC(20, 8),
    trailing_stop NUMERIC(20, 8),
    max_loss NUMERIC(20, 8), -- Maximum observed loss
    max_profit NUMERIC(20, 8), -- Maximum observed profit
    -- Metadata
    scenario_id UUID REFERENCES scenarios(scenario_id),
    strategy_type VARCHAR(50),
    ia_decision_id UUID, -- Reference to decision_logs
    status VARCHAR(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'STOPPED', 'LIQUIDATED')),
    close_reason VARCHAR(50), -- 'TAKE_PROFIT', 'STOP_LOSS', 'MANUAL', 'EXPIRY', 'LIQUIDATION'
    notes TEXT,
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for position queries
CREATE INDEX IF NOT EXISTS idx_positions_ticker ON positions (ticker);
CREATE INDEX IF NOT EXISTS idx_positions_status ON positions (status);
CREATE INDEX IF NOT EXISTS idx_positions_entry_timestamp ON positions (entry_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_positions_scenario_id ON positions (scenario_id);
CREATE INDEX IF NOT EXISTS idx_positions_realized_pnl ON positions (realized_pnl DESC NULLS LAST);

-- ====================
-- 4. ORDERS TABLE
-- ====================
-- Tracks all orders sent to broker (IBKR)
CREATE TABLE IF NOT EXISTS orders (
    order_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    position_id UUID REFERENCES positions(position_id),
    ticker VARCHAR(10) NOT NULL,
    action VARCHAR(10) NOT NULL CHECK (action IN ('BUY', 'SELL')),
    order_type VARCHAR(20) NOT NULL CHECK (order_type IN ('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'TRAILING_STOP')),
    -- Order details
    quantity NUMERIC(20, 8) NOT NULL,
    limit_price NUMERIC(20, 8),
    stop_price NUMERIC(20, 8),
    trailing_amount NUMERIC(20, 8),
    time_in_force VARCHAR(10) DEFAULT 'DAY' CHECK (time_in_force IN ('DAY', 'GTC', 'IOC', 'FOK')),
    -- Execution
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SUBMITTED', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED')),
    filled_quantity NUMERIC(20, 8) DEFAULT 0,
    avg_fill_price NUMERIC(20, 8),
    commission NUMERIC(20, 8),
    -- Broker details
    broker_order_id VARCHAR(100), -- IBKR order ID
    broker VARCHAR(20) DEFAULT 'IBKR',
    broker_response JSONB, -- Full response from broker API
    -- Risk gates
    risk_gate_soft_passed BOOLEAN DEFAULT false,
    risk_gate_hard_passed BOOLEAN DEFAULT false,
    risk_gate_override BOOLEAN DEFAULT false,
    risk_gate_reason TEXT,
    -- Timestamps
    submitted_at TIMESTAMPTZ,
    filled_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for order queries
CREATE INDEX IF NOT EXISTS idx_orders_ticker ON orders (ticker);
CREATE INDEX IF NOT EXISTS idx_orders_position_id ON orders (position_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_broker_order_id ON orders (broker_order_id);

-- ====================
-- 5. DECISION_LOGS TABLE
-- ====================
-- Logs all IA decisions with full context for learning
CREATE TABLE IF NOT EXISTS decision_logs (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    decision_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Input context
    input_pack JSONB NOT NULL, -- Full context: market data, news, indicators, etc.
    ticker VARCHAR(10),
    timeframe VARCHAR(20),
    -- Decision
    decision VARCHAR(20) NOT NULL CHECK (decision IN ('BUY', 'SELL', 'HOLD', 'CLOSE', 'WAIT')),
    decision_confidence NUMERIC(3, 2), -- 0 to 1
    decision_reasoning TEXT, -- IA explanation
    -- Associated entities
    scenario_id UUID REFERENCES scenarios(scenario_id),
    position_id UUID REFERENCES positions(position_id),
    order_id UUID REFERENCES orders(order_id),
    -- IA model info
    ia_model VARCHAR(50),
    ia_provider VARCHAR(20), -- 'anthropic', 'openai', 'local'
    ia_tokens_used INT,
    ia_cost NUMERIC(10, 6), -- Cost in USD
    ia_latency_ms INT,
    -- Outcome (filled later)
    outcome_status VARCHAR(20), -- 'SUCCESS', 'FAILURE', 'NEUTRAL', 'PENDING'
    outcome_pnl NUMERIC(20, 8),
    outcome_pnl_pct NUMERIC(10, 4),
    outcome_evaluated_at TIMESTAMPTZ,
    outcome_notes TEXT,
    -- Learning
    feedback_score INT CHECK (feedback_score >= -2 AND feedback_score <= 2), -- Human or automated feedback
    feedback_notes TEXT,
    used_for_training BOOLEAN DEFAULT false,
    -- Metadata
    environment VARCHAR(20) DEFAULT 'PAPER' CHECK (environment IN ('PAPER', 'LIVE', 'BACKTEST')),
    version VARCHAR(20),
    tags TEXT[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for decision log queries
CREATE INDEX IF NOT EXISTS idx_decision_logs_ticker ON decision_logs (ticker);
CREATE INDEX IF NOT EXISTS idx_decision_logs_decision_timestamp ON decision_logs (decision_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_decision_logs_decision ON decision_logs (decision);
CREATE INDEX IF NOT EXISTS idx_decision_logs_outcome_status ON decision_logs (outcome_status);
CREATE INDEX IF NOT EXISTS idx_decision_logs_scenario_id ON decision_logs (scenario_id);
CREATE INDEX IF NOT EXISTS idx_decision_logs_position_id ON decision_logs (position_id);
CREATE INDEX IF NOT EXISTS idx_decision_logs_ia_model ON decision_logs (ia_model);
CREATE INDEX IF NOT EXISTS idx_decision_logs_environment ON decision_logs (environment);

-- GIN index for input_pack JSONB
CREATE INDEX IF NOT EXISTS idx_decision_logs_input_pack_gin ON decision_logs USING GIN (input_pack);

-- ====================
-- 6. AGENT_PERFORMANCE TABLE
-- ====================
-- Tracks performance metrics for each IA agent/model
CREATE TABLE IF NOT EXISTS agent_performance (
    agent_name VARCHAR(50) NOT NULL,
    agent_version VARCHAR(20) NOT NULL,
    metric_date DATE NOT NULL,
    -- Call statistics
    total_calls INT DEFAULT 0,
    successful_calls INT DEFAULT 0,
    failed_calls INT DEFAULT 0,
    -- Latency
    avg_latency_ms NUMERIC(10, 2),
    p50_latency_ms INT,
    p95_latency_ms INT,
    p99_latency_ms INT,
    -- Cost
    total_tokens INT DEFAULT 0,
    total_cost_usd NUMERIC(10, 4) DEFAULT 0,
    avg_cost_per_call NUMERIC(10, 6),
    -- Decision quality
    decisions_buy INT DEFAULT 0,
    decisions_sell INT DEFAULT 0,
    decisions_hold INT DEFAULT 0,
    decisions_wait INT DEFAULT 0,
    -- Outcomes
    outcomes_success INT DEFAULT 0,
    outcomes_failure INT DEFAULT 0,
    outcomes_neutral INT DEFAULT 0,
    outcomes_pending INT DEFAULT 0,
    -- PnL (realized)
    total_pnl NUMERIC(20, 8) DEFAULT 0,
    avg_pnl NUMERIC(20, 8),
    win_rate NUMERIC(5, 4), -- % of profitable decisions
    sharpe_ratio NUMERIC(10, 4),
    max_drawdown NUMERIC(20, 8),
    -- Metadata
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (agent_name, agent_version, metric_date)
);

-- Indexes for agent performance queries
CREATE INDEX IF NOT EXISTS idx_agent_performance_agent_name ON agent_performance (agent_name);
CREATE INDEX IF NOT EXISTS idx_agent_performance_metric_date ON agent_performance (metric_date DESC);
CREATE INDEX IF NOT EXISTS idx_agent_performance_total_pnl ON agent_performance (total_pnl DESC);
CREATE INDEX IF NOT EXISTS idx_agent_performance_win_rate ON agent_performance (win_rate DESC NULLS LAST);

-- ====================
-- TRIGGERS
-- ====================

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to all tables
CREATE TRIGGER update_newscards_updated_at BEFORE UPDATE ON newscards
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_scenarios_updated_at BEFORE UPDATE ON scenarios
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_positions_updated_at BEFORE UPDATE ON positions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_decision_logs_updated_at BEFORE UPDATE ON decision_logs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ====================
-- GRANTS
-- ====================

GRANT SELECT, INSERT, UPDATE, DELETE ON newscards TO market;
GRANT SELECT, INSERT, UPDATE, DELETE ON scenarios TO market;
GRANT SELECT, INSERT, UPDATE, DELETE ON positions TO market;
GRANT SELECT, INSERT, UPDATE, DELETE ON orders TO market;
GRANT SELECT, INSERT, UPDATE, DELETE ON decision_logs TO market;
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_performance TO market;

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'Trading system tables initialized successfully!';
    RAISE NOTICE 'Created tables: newscards, scenarios, positions, orders, decision_logs, agent_performance';
END $$;
