"""
Pydantic Schemas for AI Agents
Defines structured data models for NewsCards, Scenarios, Signals, etc.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, validator


# ============================================================================
# NEWSCARD SCHEMA (Module 4: Standardizer)
# ============================================================================

class EventType(str, Enum):
    """Type of financial event"""
    PRODUCT_ANNOUNCEMENT = "product_announcement"
    EARNINGS = "earnings"
    GUIDANCE = "guidance"
    MACRO = "macro"
    LEGAL = "legal"
    REGULATORY = "regulatory"
    M_AND_A = "merger_acquisition"
    PERSONNEL = "personnel"
    SECURITY = "security_breach"
    PARTNERSHIP = "partnership"
    ANALYST = "analyst_rating"
    OTHER = "other"


class ImpactDirection(str, Enum):
    """Direction of impact on stock price"""
    POSITIVE = "positive"
    NEGATIVE = "negative"
    MIXED = "mixed"
    NEUTRAL = "neutral"


class TimeHorizon(str, Enum):
    """Time horizon for impact"""
    INTRADAY = "intraday"      # < 1 day
    DAYS = "days"              # 1-5 days
    WEEKS = "weeks"            # 1-4 weeks
    MONTHS = "months"          # 1-6 months
    LONG_TERM = "long_term"    # > 6 months


class Novelty(str, Enum):
    """Novelty of the information"""
    NEW = "new"                # Brand new information
    REPEAT = "repeat"          # Repetition of known info
    UPDATE = "update"          # Update to existing story


class NewsCard(BaseModel):
    """
    Structured representation of a financial news event
    
    Generated by Standardizer (Module 4) using LLMs (Claude/GPT)
    to transform raw text into actionable structured data.
    
    Example:
        {
            "event_id": "550e8400-e29b-41d4-a716-446655440000",
            "timestamp": "2024-12-31T14:30:00Z",
            "entities": ["Apple Inc", "Tim Cook", "iPhone 16"],
            "tickers": ["AAPL"],
            "type": "product_announcement",
            "impact_direction": "positive",
            "impact_strength": 0.75,
            "time_horizon": "weeks",
            "novelty": "new",
            "confidence": 0.85,
            "uncertainties": ["Market reception unclear", "Supply chain constraints"],
            "why_it_matters": [
                "Could boost iPhone sales 10-15% in Q2",
                "Competes directly with Samsung Galaxy S24"
            ],
            "invalidated_if": [
                "SEC rejects approval",
                "Competitor announces superior product"
            ],
            "evidence_refs": ["minio://raw-events/rss/2024/12/31/abc123.json"]
        }
    """
    
    # Identity
    event_id: str = Field(..., description="UUID of the original event")
    timestamp: datetime = Field(..., description="When the event occurred (UTC)")
    
    # Entities & Tickers
    entities: List[str] = Field(
        default_factory=list,
        description="Named entities mentioned (companies, people, products)"
    )
    tickers: List[str] = Field(
        default_factory=list,
        description="Stock tickers affected (validated against whitelist)"
    )
    
    # Classification
    type: EventType = Field(..., description="Type of financial event")
    impact_direction: ImpactDirection = Field(..., description="Expected price impact direction")
    impact_strength: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Strength of impact (0.0 = negligible, 1.0 = major)"
    )
    time_horizon: TimeHorizon = Field(..., description="Expected time horizon for impact")
    novelty: Novelty = Field(..., description="Novelty of the information")
    
    # Confidence & Uncertainty
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="LLM confidence in analysis (calibrated)"
    )
    uncertainties: List[str] = Field(
        default_factory=list,
        description="Key uncertainties that could change the outcome"
    )
    
    # Reasoning
    why_it_matters: List[str] = Field(
        ...,
        min_items=1,
        max_items=10,
        description="3-5 bullet points explaining significance"
    )
    invalidated_if: List[str] = Field(
        default_factory=list,
        description="Conditions that would invalidate this analysis"
    )
    
    # References
    evidence_refs: List[str] = Field(
        default_factory=list,
        description="References to source material (MinIO URIs, URLs)"
    )
    
    # Metadata (added by system, not LLM)
    source_type: Optional[str] = Field(None, description="Source type (rss, reddit, etc.)")
    source_name: Optional[str] = Field(None, description="Source name (bloomberg.com, etc.)")
    model_used: Optional[str] = Field(None, description="LLM model used for generation")
    generation_cost_usd: Optional[float] = Field(None, description="Cost of LLM call")
    created_at: Optional[datetime] = Field(default_factory=datetime.utcnow)
    
    @validator("why_it_matters")
    def validate_why_it_matters(cls, v):
        """Ensure why_it_matters has reasonable length"""
        if len(v) < 1:
            raise ValueError("why_it_matters must have at least 1 item")
        if len(v) > 10:
            raise ValueError("why_it_matters should have max 10 items (aim for 3-5)")
        return v
    
    @validator("tickers")
    def validate_tickers_format(cls, v):
        """Ensure tickers are uppercase"""
        return [ticker.upper() for ticker in v]
    
    class Config:
        json_schema_extra = {
            "example": {
                "event_id": "550e8400-e29b-41d4-a716-446655440000",
                "timestamp": "2024-12-31T14:30:00Z",
                "entities": ["Apple Inc", "Tim Cook", "iPhone 16"],
                "tickers": ["AAPL"],
                "type": "product_announcement",
                "impact_direction": "positive",
                "impact_strength": 0.75,
                "time_horizon": "weeks",
                "novelty": "new",
                "confidence": 0.85,
                "uncertainties": ["Market reception unclear"],
                "why_it_matters": [
                    "Could boost iPhone sales 10-15% in Q2",
                    "Introduces AI features ahead of competitors"
                ],
                "invalidated_if": ["Delayed launch announcement"],
                "evidence_refs": ["minio://raw-events/rss/2024/12/31/abc123.json"]
            }
        }


# ============================================================================
# SCENARIO SCHEMA (Module 5: Plan Builder)
# ============================================================================

class ScenarioBias(str, Enum):
    """Directional bias of scenario"""
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"


class Scenario(BaseModel):
    """
    Strategic scenario for a ticker
    
    Generated pre-market (04:00 ET) by Plan Builder
    Contains conditions, targets, and invalidation criteria
    """
    
    scenario_id: str = Field(..., description="Unique scenario identifier")
    ticker: str = Field(..., description="Stock ticker")
    name: str = Field(..., description="Human-readable scenario name")
    version: str = Field(..., description="Version (incremented on updates)")
    
    # Directional
    bias: ScenarioBias = Field(..., description="Bullish/bearish/neutral bias")
    probability: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Estimated probability (0-1)"
    )
    
    # Conditions
    entry_conditions: List[str] = Field(
        ...,
        description="Conditions that trigger entry"
    )
    invalidation_triggers: List[str] = Field(
        ...,
        description="Conditions that invalidate scenario"
    )
    
    # Targets
    targets: Dict[str, float] = Field(
        ...,
        description="Price targets (entry, stop, take_profit_1, take_profit_2)"
    )
    
    # Risk
    size_max_pct: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Maximum position size as % of portfolio"
    )
    
    # Timing
    time_horizon: TimeHorizon = Field(..., description="Expected time horizon")
    reassess_if: List[str] = Field(
        default_factory=list,
        description="Events that require reassessment"
    )
    
    # Reasoning
    reasoning: List[str] = Field(
        ...,
        description="Step-by-step reasoning for scenario"
    )
    
    # Catalysts
    catalysts_pending: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Upcoming catalysts (earnings, Fed meetings, etc.)"
    )
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    superseded_by: Optional[str] = Field(None, description="ID of newer version")
    
    class Config:
        json_schema_extra = {
            "example": {
                "scenario_id": "AAPL_bullish_q1_2025_v1",
                "ticker": "AAPL",
                "name": "iPhone 16 Supercycle",
                "version": "1",
                "bias": "bullish",
                "probability": 0.65,
                "entry_conditions": [
                    "Break above $195 with volume",
                    "Positive guidance from management"
                ],
                "invalidation_triggers": [
                    "Close below $185",
                    "Guidance miss > 5%"
                ],
                "targets": {
                    "entry": 195.0,
                    "stop_loss": 185.0,
                    "take_profit_1": 205.0,
                    "take_profit_2": 215.0
                },
                "size_max_pct": 0.10,
                "time_horizon": "weeks",
                "reassess_if": ["Earnings report", "New product delay"],
                "reasoning": [
                    "Strong iPhone 16 pre-orders",
                    "AI features driving upgrade cycle"
                ],
                "catalysts_pending": [
                    {"type": "earnings", "date": "2025-01-30"}
                ]
            }
        }


# ============================================================================
# SIGNAL SCHEMA (Module 6: Decision Engine)
# ============================================================================

class SignalAction(str, Enum):
    """Trading action"""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderType(str, Enum):
    """Order type"""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class Signal(BaseModel):
    """
    Trading signal generated by Decision Engine
    
    Final output after LangGraph workflow evaluation
    """
    
    signal_id: str = Field(..., description="Unique signal identifier")
    ticker: str = Field(..., description="Stock ticker")
    action: SignalAction = Field(..., description="BUY/SELL/HOLD")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Decision confidence")
    
    # Execution Plan
    plan: Dict[str, Any] = Field(
        ...,
        description="Execution parameters (order_type, quantity, limits, etc.)"
    )
    
    # Reasoning
    reasoning: List[str] = Field(..., description="Decision reasoning chain")
    matched_scenarios: List[str] = Field(
        default_factory=list,
        description="Scenario IDs that matched"
    )
    
    # Risk
    risk_score: float = Field(..., ge=0.0, le=1.0, description="Risk assessment score")
    risk_checks_passed: List[str] = Field(
        default_factory=list,
        description="Risk checks that passed"
    )
    
    # Metadata
    created_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = Field(None, description="Signal expiration")
    
    class Config:
        json_schema_extra = {
            "example": {
                "signal_id": "signal_aapl_20250131_143000",
                "ticker": "AAPL",
                "action": "BUY",
                "confidence": 0.78,
                "plan": {
                    "order_type": "LIMIT",
                    "quantity": 10,
                    "limit_price": 195.50,
                    "stop_loss": 185.00,
                    "take_profit": [200.0, 205.0]
                },
                "reasoning": [
                    "Scenario 'iPhone 16 Supercycle' entry triggered",
                    "Technical confirmation: RSI > 50, MACD crossover",
                    "NewsCard confidence aggregate: 0.82"
                ],
                "matched_scenarios": ["AAPL_bullish_q1_2025_v1"],
                "risk_score": 0.35,
                "risk_checks_passed": [
                    "position_size_ok",
                    "correlation_ok",
                    "regime_ok"
                ]
            }
        }
